# Generated by Django 5.1.3 on 2024-11-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonsulting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingservice',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на изображение услуги', null=True),
        ),
    ]
