# Generated by Django 5.1.3 on 2024-11-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonsulting', '0002_consultingservice_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'service_requests',
            },
        ),
        migrations.RemoveConstraint(
            model_name='consultingrequest',
            name='unique_service_request',
        ),
        migrations.RemoveField(
            model_name='consultingrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='consultingrequest',
            name='service',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='сonsulting.consultingrequest'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='сonsulting.consultingservice'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequest',
            unique_together={('request', 'service')},
        ),
    ]
