# Generated by Django 5.1.3 on 2024-11-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonsulting', '0003_servicerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
