# Generated by Django 5.1.3 on 2024-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonsulting', '0006_remove_consultingrequest_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Draft', max_length=9),
        ),
    ]
