# Generated by Django 5.1.3 on 2024-12-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonsulting', '0007_alter_consultingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingrequest',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
