# Generated by Django 5.1.3 on 2024-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonsulting', '0004_servicerequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingrequest',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
