# Generated by Django 5.1.3 on 2024-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonsulting', '0005_alter_consultingrequest_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultingrequest',
            name='client_email',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
